
export const INCREMENT_DATA = 'INCREMENT_DATA'
export const DECREMENT_DATA = 'DECREMENT_DATA'

export const GET_MEDICINES = 'GET_MEDICINES'
export const LOADING_MEDICINE = 'LOADING_MEDICINE'
export const ERROR_MEDICINE = 'ERROR_MEDICINE'